// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_login from "./routes/api/login.ts";
import * as $api_questions from "./routes/api/questions.ts";
import * as $api_submit from "./routes/api/submit.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $quiz from "./routes/quiz.tsx";
import * as $Quiz from "./islands/Quiz.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/login.ts": $api_login,
    "./routes/api/questions.ts": $api_questions,
    "./routes/api/submit.ts": $api_submit,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/quiz.tsx": $quiz,
  },
  islands: {
    "./islands/Quiz.tsx": $Quiz,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
